# Generated by Django 3.2 on 2021-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210621_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='мой аватар'),
        ),
    ]
