# Generated by Django 3.2 on 2021-06-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='user_photo',
        ),
    ]
